# Generated by Django 4.1.3 on 2022-12-12 12:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_like_user_like_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='resized_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[500, 300], upload_to='photos/posts/resized/%Y/%m/%d'),
        ),
    ]
