# Generated by Django 4.1.3 on 2022-12-13 11:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_image_resized_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='resized_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=50, scale=0.5, size=[1000, 750], upload_to='photos/posts/resized/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default='About user'),
        ),
    ]
