# Generated by Django 4.1.3 on 2022-12-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='tag_title',
        ),
    ]
