# Generated by Django 4.1.3 on 2022-12-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_title_tag_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=250, verbose_name='Tags'),
        ),
    ]
